// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightThemeSix from '@six-tech/starlight-theme-six';

// The pages under src/content/docs/ are GENERATED by `/docs-site --starlight`
// from the markdown in docs/. Edit docs/*.md, then rebuild. Anything typed
// into src/content/docs/ is overwritten on the next run.
//
// No sidebar is configured on purpose: with none set, Starlight builds one
// from the file structure, using each page's title. Adding files to docs/ is
// therefore all it takes to get them into the navigation.
export default defineConfig({
  // Set `site` once the documentation has a URL. Without it the sitemap
  // integration skips itself and warns on every build.
  // site: 'https://docs.example.com',
  // Astro 7 minifies CSS with lightningcss, which rejects a selector in the
  // Starlight Six theme's generated CSS ("Pseudo-elements like '::before'
  // can't be followed by selectors like 'Colon'") and fails the whole build.
  // esbuild minifies the same CSS without complaint. Remove this once Six
  // ships CSS lightningcss accepts.
  vite: {
    build: { cssMinify: 'esbuild' },
  },
  integrations: [
    starlight({
      title: '{{PROJECT_NAME}}',
      description: '{{PROJECT_DESCRIPTION}}',
      // Set this if the site is served from a subdirectory rather than a
      // domain root, for example GitHub Pages.
      // base: '/docs',
{{LOGO_CONFIG}}
      // Starlight Six ships two unlabelled buttons in its mobile drawer
      // (.sheet-overlay and .drag-icon), which Lighthouse scores as
      // "Buttons do not have an accessible name". That drops accessibility
      // from 100 to 94 and malforms the accessibility tree. Both buttons close
      // the drawer, so both get the same name. Remove this once Six labels
      // them upstream.
      head: [
        {
          tag: 'script',
          content: `
            document.addEventListener('DOMContentLoaded', () => {
              document
                .querySelectorAll('button.sheet-overlay, button.drag-icon')
                .forEach((b) => {
                  if (!b.getAttribute('aria-label')) {
                    b.setAttribute('aria-label', 'Close navigation');
                  }
                });
            });
          `,
        },
      ],
      plugins: [
        // The object is required. Calling starlightThemeSix() with no argument
        // throws "expected object, received undefined", even though every
        // option inside it is optional.
        starlightThemeSix({
          // Six defaults this to its own credit line. Overridden so a client's
          // documentation does not carry a third party's marketing.
          footerText: '{{PROJECT_NAME}} documentation.',
        }),
      ],
      customCss: [
        // Generated. The brand accent, rebuilt from the project's own primary
        // colour on every run. Do not hand-edit.
        './src/styles/brand.css',
        // Yours. Never overwritten.
        './src/styles/custom.css',
      ],
    }),
  ],
});
