// Required by Starlight. Without it the docs collection is empty and the build
// produces a 404 page and nothing else.
//
// The pages this loads from src/content/docs/ are GENERATED by
// `/docs-site --starlight` from the markdown in docs/. Edit docs/*.md.
import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
